name: Scheduled Merge Remote Action
on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main # set the branch to merge to
          fetch-depth: 0
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: https://github.com/rust-multiplatform/Base-Project-Template # set the upstream repo
          upstream-branch: main # set the upstream branch to merge from
          branch: main # set the branch to merge to
